export const assets = {
  guitarSoundhole: "/assets/guitar-soundhole.png",
  heroLogin: "/assets/hero-login.jpeg",
  paperTexture: "/assets/paper-texture.jpeg",
  avatar: "/assets/avatar.png",
  grandPiano: "/assets/grand-piano.jpg",
  notesCluster: "/assets/notes-cluster.png",
  guitarWide: "/assets/guitar-wide.png",
  guitarNeck: "/assets/guitar-neck.png",
  heroPassword: "/assets/hero-password.jpeg",
  loginFrameBg: "/assets/login-frame-bg.png",
  pianoGuitarBg: "/assets/piano-guitar-bg.png",
  violin: "/assets/violin.jpg",
  playButton: "/assets/play-button.png",
  waveformGold: "/assets/waveform-gold.png",
  loaderClef: "/assets/loader-clef.png",
  notesLoader: "/assets/notes-loader.png",
  vinyl: "/assets/vinyl.png",
  notesSmall: "/assets/notes-small.png",
};
